version: "3.8"

## Network
networks:
  fit_a_pet:
    driver: bridge
    external: true

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: root
    env_file:
      - ./data/grafana/env.grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - fit_a_pet
