version: "3.8"

## Network
networks:
  fit_a_pet:
    driver: bridge
    external: true

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: root
    env_file:
      - ./data/grafana/env.grafana
    ports:
      - "3000:3000"
    volumes:
      - ./data/grafana:/var/lib/grafana
    networks:
      - fit_a_pet

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always
    networks:
      - fit_a_pet
